### ISSUE TITLE
feature: support dynamic completions and delegation

### ISSUE THREAD

**Issue by davidovich** [davidovich/summon#67]
Allow calling into a user defined completion program (including self references).

This will require changing the format of the invocables to allow further customizations (help, completion hook, cmd etc.)

A design will follow.

Dynamic completion from cobra: 

https://github.com/spf13/cobra/blob/master/shell_completions.md#customizing-completions

**Comment by davidovich** [comment]
Example config file changes, addittions:

```yaml
  manifest2:
    help: 'render kubernetes manifests in build dir'
    cmdArgs: [*baseargs, 'manifests/{{arg 0 "manifest"}}','{{ template "parseArgs" 1 }}']
    completion: '{{ summon "make list-environments" }}'

  build2:
    help: 'build components'
    cmdArgs: &build2 [*baseargs, 'build/{{arg 0 "build"}}','{{ template "--config-root"}}']
    args:
      - image:
          cmdArgs: [*baseargs, 'build/image/{{arg 0 "build image"}}']
          help: "build images in this repo"
          completion: '{{ summon "make to-do-implement-image-list" }}'

      - gitlab-ci.yaml:
          flags:
            --one-pipeline: '{{ define "--one-pipeline" }}{{ if eq . "true"}} PARENT_CHILD=0 {{ else }} PARENT_CHILD=1 {{ end }}'
          cmdArgs: [*build2, '{{ template "--one-pipeline" }}']
          help: "Initialize or merge gitlab-ci.yaml"

      # call internal helper to complete the generic target list
      - '{{ summon "make list-build-targets" }}'

flags:
  --config-root: '{{ define "--config-root" }}CONFIG_ROOT=.{{ end }}'
```

This supposes the following changes:

* harvest every explicit flags and configure cobra accordingly. We probably need to specify the type of destination, but at first support `string`
* allow for complex command args definition, in addition to, simple array definitions
* make a global argsDict available to commands
* hook dynamic completions on cobra completions
